
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[223] =
    {   0,
        0,    0,   67,   65,    3,    2,   51,   65,   65,   42,
       65,   65,   45,   46,   38,   39,   47,   40,   41,   65,
       62,   44,   55,   43,   53,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   48,   50,   49,   56,   64,    0,   60,
       57,    0,    0,   62,    1,    0,    0,   64,   64,   62,
       64,   54,   58,   52,   64,   63,   63,   63,   63,   63,
       63,   63,   12,   63,   63,   63,   63,   63,   63,   20,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   64,   59,   62,    0,    1,   64,

       61,    0,   64,   62,   64,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   18,   63,   21,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,    0,   62,    0,   61,
       62,    5,   63,    7,    8,   63,   63,   63,   63,   14,
       15,   63,   63,   19,   22,    4,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   35,   63,
       63,   62,    0,    0,   61,    6,    9,   63,   63,   63,
       63,   17,   63,   63,   25,   26,   63,   63,   63,   63,
       63,   63,   33,   63,   63,   37,   61,   63,   63,   13,

       16,   24,   63,   27,   28,   29,   30,   31,   63,   63,
       63,   63,   11,   63,   32,   63,   63,   10,   23,   34,
       36,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    6,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   20,   20,    6,   21,   22,
       23,   24,    1,    6,   25,   25,   25,   26,   27,   25,
       25,   25,   25,   25,   25,   28,   29,   25,   25,   25,
       25,   25,   29,   25,   25,   25,   25,   25,   29,   25,
        1,    1,    1,    1,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   25,   40,   41,   42,   43,
       44,   45,   25,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[58] =
    {   0,
        1,    1,    2,    3,    1,    3,    1,    1,    1,    1,
        1,    1,    1,    4,    1,    4,    1,    5,    5,    5,
        1,    1,    6,    1,    7,    7,    7,    7,    7,    8,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    1,    1,    1
    } ;

static const flex_int16_t yy_base[230] =
    {   0,
        0,    0,  190,  723,  723,  723,  166,  177,  154,  723,
      165,    0,  723,  723,  723,   40,  723,   43,  147,   50,
       57,  723,  134,  131,  130,   61,   68,   74,   75,   79,
       83,   84,   87,   91,   92,   98,   95,  103,  104,  112,
      126,  140,  141,  723,  723,  723,  723,    0,  135,  134,
      723,  124,   99,  140,    0,  123,  143,  152,   89,    0,
      172,  723,  723,  723,  170,  144,  189,  177,  196,  197,
      201,  200,  204,  205,  209,  212,  213,  216,  217,  220,
      225,  226,  229,  235,  234,  241,  242,  245,  250,  255,
      260,  271,  272,  281,    0,  723,  273,  282,    0,  723,

      296,   92,  293,  308,  299,  300,  329,  332,  284,  335,
      339,  336,  342,  343,  346,  347,  351,  355,  358,  359,
      365,  368,  380,  369,  383,  384,  387,  388,  391,  394,
      397,  400,  409,  401,  410,  414,   74,   68,  411,  723,
      407,  433,  439,  443,  446,  447,  450,  453,  456,  457,
      460,  461,  464,  465,  468,  469,  472,  476,  477,  480,
      481,  486,  487,  492,  499,  495,  500,  504,  505,  511,
      515,   60,  102,   56,  498,  527,  531,  532,  536,  541,
      540,  545,  548,  549,  552,  556,  557,  560,  561,  564,
      565,  574,  568,  575,  581,  582,  563,  586,  589,  594,

      601,  602,  607,  610,  611,  615,  618,  619,  622,  625,
      626,  630,  634,  635,  639,  640,  643,  644,  647,  648,
      651,  723,  676,  684,  692,  697,  702,  706,  714
    } ;

static const flex_int16_t yy_def[230] =
    {   0,
      222,    1,  222,  222,  222,  222,  223,  224,  223,  222,
      222,  225,  222,  222,  222,  222,  222,  222,  222,  226,
      226,  222,  222,  222,  222,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  222,  222,  222,  222,  228,  224,  224,
      222,  222,  222,  222,  229,  222,  222,  226,  226,   21,
      226,  222,  222,  222,  222,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  228,  222,  222,  222,  229,  222,

      222,  222,  226,  226,  222,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  222,  222,  222,  222,
      226,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  222,  222,  222,  222,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  222,  227,  227,  227,

      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,    0,  222,  222,  222,  222,  222,  222,  222
    } ;

static const flex_int16_t yy_nxt[781] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,    4,   19,   20,   21,   21,
       22,   23,   24,   25,   26,   26,   26,   26,   26,   26,
       27,   28,   29,   30,   31,   32,   33,   26,   34,   26,
       35,   36,   26,   26,   37,   38,   39,   40,   41,   42,
       43,   26,   26,   26,   44,   45,   46,   53,   54,   54,
       53,   54,   54,   56,   65,   57,   65,   58,   58,   58,
       56,   65,   57,   65,   60,   60,   60,   65,   65,   65,
       65,  197,   65,   61,   65,  172,   65,   65,   65,   65,
       65,   61,   65,  172,   65,   65,   65,   65,   65,  172,

       65,   65,  222,   65,  222,   69,   65,   65,   65,   65,
      137,  138,   70,   72,   57,   65,   67,   65,   71,   68,
      174,  175,   73,   74,   77,   75,   80,   78,   83,   65,
       79,   65,   96,   81,   76,   82,   86,   85,   50,   50,
       84,   87,   88,   65,   65,   65,   65,   65,  100,   65,
      100,   89,   64,   63,   90,   57,   62,   97,   97,   97,
      101,  101,  101,   55,   91,   56,   98,  222,   92,   58,
       58,   58,   51,   65,   98,   65,  222,  100,   94,  100,
       65,   50,   65,   93,  102,  222,  102,  222,   47,  222,
      103,  104,   65,  222,   65,  105,  222,  105,  105,   65,

       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,  107,   65,  222,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,  105,   65,  105,  109,   65,   65,
       65,   65,   65,  222,   65,  111,  106,   65,   65,   65,
       65,  222,  108,  110,   65,   65,   65,   65,   65,  222,
       65,  113,  112,   65,  222,   65,  116,  114,   65,  115,
       65,  117,  222,   65,  118,   65,  222,  121,  120,  222,
      123,  124,  119,  122,   65,   65,   65,   65,  222,  222,
      128,  126,  222,  222,   65,  125,   65,   65,   57,   65,
       97,   97,   97,  130,  102,  129,  102,  222,  127,   98,

      137,  138,  222,   65,  131,   65,  222,   98,  222,  132,
      134,  222,  135,  101,  101,  101,  222,  133,  141,  136,
      222,  222,  139,  222,  105,  222,  105,  105,  222,  145,
      139,  140,   65,  141,   65,   65,  140,   65,   65,   65,
       65,   65,   65,  142,   65,   65,   65,   65,   65,   65,
       65,   65,   65,  105,   65,  105,   65,  222,   65,  143,
       65,   65,   65,   65,   65,  222,  144,  149,   65,  148,
       65,   65,   65,   65,   65,  222,  150,  153,  222,  222,
      152,  146,  147,   65,  151,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,  155,   65,   65,  154,   65,

       65,  222,   65,   65,   65,   65,   65,  156,  222,  222,
      157,  159,   65,   65,   65,   65,  222,   65,  158,   65,
      222,  162,  222,  173,  222,  173,  161,  222,  160,  174,
      175,  166,  141,  222,  169,  163,   65,  222,   65,  164,
      170,  165,   65,  167,   65,  222,   65,  168,   65,   65,
       65,   65,   65,   65,  171,   65,   65,  222,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,  222,   65,  176,   65,
       65,   65,   65,   65,   65,   65,   65,  222,  178,   65,
       65,   65,   65,  222,  177,   65,  180,   65,   65,  222,

       65,  179,   65,   65,   65,   65,  181,   65,   65,   65,
       65,  182,  185,  222,   65,  187,   65,  222,   65,  183,
       65,  222,  184,  197,  190,  189,  222,  186,  192,  188,
       65,  191,   65,  140,   65,   65,   65,   65,  140,   65,
      194,   65,  193,   65,   65,   65,   65,  222,   65,  196,
       65,   65,   65,   65,   65,   65,  222,   65,  195,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,  222,   65,  198,  200,  199,   65,   65,   65,
       65,  222,  201,  202,   65,   65,   65,   65,  197,   65,
      204,   65,   65,  206,   65,  205,  203,   65,  140,   65,

      222,  222,  208,  140,   65,   65,   65,   65,  209,  222,
       65,  207,   65,   65,   65,   65,   65,  210,   65,  211,
       65,   65,   65,   65,   65,   65,  222,   65,   65,   65,
       65,   65,  222,   65,  212,   65,  213,   65,   65,   65,
       65,  214,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,  222,   65,  215,  222,  216,
      222,  222,  222,  222,  218,  222,  217,  222,  222,  222,
      222,  222,  222,  220,  222,  222,  222,  221,  222,  222,
      219,   48,   48,   48,   49,  222,   49,   49,   49,   49,
       49,   49,   52,  222,   52,   52,   52,   52,   52,   52,

       59,   59,  222,   59,   66,  222,   66,  222,   66,   66,
       95,  222,   95,   95,   99,  222,   99,   99,   99,   99,
       99,   99,    3,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222
    } ;

static const flex_int16_t yy_chk[781] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   16,   16,   16,
       18,   18,   18,   20,   26,   20,   26,   20,   20,   20,
       21,   27,   21,   27,   21,   21,   21,   28,   29,   28,
       29,  174,   30,   21,   30,  172,   31,   32,   31,   32,
       33,   21,   33,  138,   34,   35,   34,   35,   37,  137,

       37,   36,   59,   36,   59,   29,   38,   39,   38,   39,
      102,  102,   29,   30,   53,   40,   27,   40,   29,   28,
      173,  173,   30,   31,   32,   31,   34,   32,   36,   41,
       33,   41,   52,   34,   31,   35,   39,   38,   50,   49,
       37,   39,   39,   42,   43,   42,   43,   66,   56,   66,
       56,   39,   25,   24,   39,   54,   23,   54,   54,   54,
       57,   57,   57,   19,   40,   58,   54,   58,   41,   58,
       58,   58,   11,   65,   54,   65,    9,   56,   43,   56,
       68,    8,   68,   42,   61,   61,   61,   61,    7,    3,
       61,   61,   67,    0,   67,   65,    0,   65,   65,   69,

       70,   69,   70,   72,   71,   72,   71,   73,   74,   73,
       74,   68,   75,    0,   75,   76,   77,   76,   77,   78,
       79,   78,   79,   80,   65,   80,   65,   70,   81,   82,
       81,   82,   83,    0,   83,   72,   67,   85,   84,   85,
       84,    0,   69,   71,   86,   87,   86,   87,   88,    0,
       88,   74,   73,   89,    0,   89,   77,   75,   90,   76,
       90,   78,    0,   91,   79,   91,    0,   83,   82,    0,
       85,   86,   81,   84,   92,   93,   92,   93,    0,    0,
       89,   88,    0,    0,   94,   87,   94,  109,   97,  109,
       97,   97,   97,   90,   98,   89,   98,    0,   88,   97,

       98,   98,    0,  106,   91,  106,  103,   97,  103,   92,
       93,    0,   93,  101,  101,  101,    0,   92,  103,   94,
        0,  104,  101,  104,  105,    0,  105,  105,    0,  109,
      101,  101,  107,  104,  107,  108,  101,  108,  110,  112,
      110,  112,  111,  106,  111,  113,  114,  113,  114,  115,
      116,  115,  116,  105,  117,  105,  117,    0,  118,  107,
      118,  119,  120,  119,  120,    0,  108,  112,  121,  111,
      121,  122,  124,  122,  124,    0,  113,  116,    0,    0,
      115,  110,  110,  123,  114,  123,  125,  126,  125,  126,
      127,  128,  127,  128,  129,  120,  129,  130,  118,  130,

      131,    0,  131,  132,  134,  132,  134,  121,    0,    0,
      122,  124,  133,  135,  133,  135,    0,  136,  123,  136,
      141,  127,  141,  139,    0,  139,  126,    0,  125,  139,
      139,  131,  141,    0,  134,  128,  142,    0,  142,  129,
      135,  130,  143,  132,  143,    0,  144,  133,  144,  145,
      146,  145,  146,  147,  136,  147,  148,    0,  148,  149,
      150,  149,  150,  151,  152,  151,  152,  153,  154,  153,
      154,  155,  156,  155,  156,  157,    0,  157,  143,  158,
      159,  158,  159,  160,  161,  160,  161,    0,  147,  162,
      163,  162,  163,    0,  146,  164,  149,  164,  166,    0,

      166,  148,  165,  167,  165,  167,  152,  168,  169,  168,
      169,  153,  159,    0,  170,  161,  170,    0,  171,  157,
      171,    0,  158,  175,  164,  163,    0,  160,  166,  162,
      176,  165,  176,  175,  177,  178,  177,  178,  175,  179,
      168,  179,  167,  181,  180,  181,  180,    0,  182,  171,
      182,  183,  184,  183,  184,  185,    0,  185,  170,  186,
      187,  186,  187,  188,  189,  188,  189,  190,  191,  190,
      191,  193,    0,  193,  178,  180,  179,  192,  194,  192,
      194,    0,  181,  183,  195,  196,  195,  196,  197,  198,
      187,  198,  199,  189,  199,  188,  184,  200,  197,  200,

        0,    0,  191,  197,  201,  202,  201,  202,  192,    0,
      203,  190,  203,  204,  205,  204,  205,  194,  206,  195,
      206,  207,  208,  207,  208,  209,    0,  209,  210,  211,
      210,  211,    0,  212,  198,  212,  199,  213,  214,  213,
      214,  203,  215,  216,  215,  216,  217,  218,  217,  218,
      219,  220,  219,  220,  221,    0,  221,  209,    0,  210,
        0,    0,    0,    0,  212,    0,  211,    0,    0,    0,
        0,    0,    0,  216,    0,    0,    0,  217,    0,    0,
      214,  223,  223,  223,  224,    0,  224,  224,  224,  224,
      224,  224,  225,    0,  225,  225,  225,  225,  225,  225,

      226,  226,    0,  226,  227,    0,  227,    0,  227,  227,
      228,    0,  228,  228,  229,    0,  229,  229,  229,  229,
      229,  229,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  222,  222
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "LAB01_Blanco_Cespedes_DiSilvio.lex"
#line 2 "LAB01_Blanco_Cespedes_DiSilvio.lex"
// Definitons, can be accessed inside yylex() and main()
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include "Node.h"

Node *head_errors;
Node *head_id;
int number_id = 0;
int number_errors = 0;
#line 697 "lex.yy.c"
/* regular definitions */
#line 699 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 27 "LAB01_Blanco_Cespedes_DiSilvio.lex"


#line 919 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 223 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 723 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "LAB01_Blanco_Cespedes_DiSilvio.lex"
;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 30 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"\n");
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{/* Just ignore whitespaces*/}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"MAIN \n"); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 33 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"AUTO "); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 34 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"BREAK "); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"CASE "); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 36 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"CHAR "); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"CONST "); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 38 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"CONTINUE "); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 39 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"DEFAULT "); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 40 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"DO "); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 41 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"DOUBLE "); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 42 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"ELSE "); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 43 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"ENUM "); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 44 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"EXTERN "); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 45 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"FLOAT "); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 46 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"FOR "); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 47 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"GOTO "); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"IF "); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"INT "); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"LONG "); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"REGISTER "); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 52 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"PRINTF "); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 53 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"SCANF "); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 54 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"SHORT "); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 55 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"SIGNED "); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 56 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"SIZEOF "); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 57 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"STATIC "); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 58 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"STRUCT "); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 59 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"SWITCH "); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 60 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"TYPEDEF "); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 61 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"UNION "); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 62 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"UNSIGNED "); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 63 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"VOID "); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 64 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"VOLATILE "); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 65 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{  fprintf(yyout,"WHILE "); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 66 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"op-mult= %s", yytext);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 67 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"op-sum= %s ", yytext);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 68 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"op-sust= %s ", yytext);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 69 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"op-div= %s ", yytext);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 70 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"op-mod= %s ", yytext);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 71 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"op-asig= %s ", yytext);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 72 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"Punto-coma= %s ", yytext);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 73 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"Parent-a= %s ", yytext);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 74 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"Parent-c= %s ", yytext);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 75 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"coma= %s ", yytext);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 76 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"Inicio= %s ", yytext);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 77 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"Fin= %s ", yytext);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 78 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"op-or= %s ", yytext);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 79 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"op-neg= %s ", yytext);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 80 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"op-maq= %s ", yytext);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 81 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"op-may= %s ", yytext);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 82 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"op-meq= %s ", yytext);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 83 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"op-men= %s ", yytext);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 84 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"op-dist= %s ", yytext);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 85 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"op-and= %s ", yytext);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 86 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"op-igu= %s ", yytext);
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 87 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"Cte-cara= %s ", yytext);
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 88 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"Cte-cade= %s ", yytext);
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 89 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"Cte-real= %s ", yytext);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 90 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"Cte-ent= %s ", yytext);
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 91 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{ fprintf(yyout,"Id= %s ", yytext); number_id = append(head_id,number_id); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 92 "LAB01_Blanco_Cespedes_DiSilvio.lex"
{ fprintf(yyout,"Error= %s ", yytext); number_errors = append(head_errors,number_errors); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 93 "LAB01_Blanco_Cespedes_DiSilvio.lex"
fprintf(yyout,"");
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 94 "LAB01_Blanco_Cespedes_DiSilvio.lex"
ECHO;
	YY_BREAK
#line 1307 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 223 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 223 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 222);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 94 "LAB01_Blanco_Cespedes_DiSilvio.lex"


int yywrap(){}

int append(Node *head, int cantidad)
{	
	Node *temp = NULL;
	temp = (Node*)malloc(sizeof(Node));
	Node *p = head;
	while(p->next != NULL)
	{
		if(strcmp(p->text,yytext) == 0)
		{
			return cantidad;
		}
		p = p->next;
	}
	if(strcmp(p->text,yytext) == 0)
	{
		return cantidad;
	}
	p->next = temp;
	temp->next = NULL;
	strcpy(temp->text,yytext);
	return cantidad + 1;
}

void printList(Node *head, FILE *f, int opt){
	int i = 1;
	Node *p = head->next;
	while(p != NULL)
	{
		if(opt == 1){
			fprintf(f,"Id-%d= %s;  ",i,p->text);
		}else{
			fprintf(f,"Error-%d= %s;  ",i,p->text);
		}
		i = i + 1;
		p = p->next;
	}
	fprintf(f,"\n");
}

int main(int argc, char* argv[])
{
	if (argc > 1)
	{
		FILE *fp = fopen(argv[1], "r");
		if(fp)
		{
			yyin = fp;
		}
	}
	FILE *fp2 = fopen("salida.txt","w");
	yyout = fp2;
	head_id = (Node*)malloc(sizeof(Node));
    head_errors = (Node*)malloc(sizeof(Node));
	yylex();
	fprintf(fp2,"Hay un total de %d identificadores \n", number_id);
	printList(head_id,fp2,1);
	fprintf(fp2,"Hay un total de %d errores lexicos \n", number_errors);
	printList(head_errors,fp2,0);
	fclose(fp2);
	return 0;
}

